### ISSUE TITLE
buck data download and problems in running marinetrophicindex() 

### ISSUE THREAD

**Issue by Xeonilian** [ropensci/seaaroundus#11]
Hi, I requsted bulk data of marine trophic index through the Sea Around Us website, and was lead to this page. After installing the R library and running all examples, I found 
the function marinetrophicindex() didn’t work (Windows).
``
> marinetrophicindex("eez", 76)
#No encoding supplied: defaulting to UTF-8.
Error in named_data[[type]] : subscript out of bounds

> marinetrophicindex("eez", 76, type = "rmti")
No encoding supplied: defaulting to UTF-8.
Error in named_data[["RMTI_1950"]] : subscript out of bounds

> marinetrophicindex("eez", 76, type = "fib_index")
No encoding supplied: defaulting to UTF-8.
Error in named_data[[type]] : subscript out of bounds

Besides, the functions listregions(), catchdata() and getcells() worked. 
Do you have any clue what I might do run, and how can I solve the problem?
Thank you very much!

**Comment by sckott** [comment]
thanks @Xeonilian - looking into it, plz share your R session info - past in output of `sessionInfo()`

**Comment by Xeonilian** [comment]
This is my R session info
`> sessionInfo()`

> R version 3.3.2 (2016-10-31)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> locale:
> [1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
> [3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
> [5] LC_TIME=Chinese (Simplified)_China.936    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] seaaroundus_1.0.0
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.8      lattice_0.20-34  withr_1.0.2      digest_0.6.11    assertthat_0.1   grid_3.3.2       plyr_1.8.4      
>  [8] R6_2.2.0         jsonlite_1.3     gtable_0.2.0     scales_0.4.1     ggplot2_2.2.1    httr_1.2.1       curl_2.3        
> [15] lazyeval_0.2.0   sp_1.2-4         devtools_1.12.0  rgdal_1.2-5      tools_3.3.2      munsell_0.4.3    maps_3.1.1      
> [22] colorspace_1.3-2 memoise_1.0.0    tibble_1.2

**Comment by patperu** [comment]
Hi @Xeonilian, 
using the development version `ropensci/rseaaroundus@d405c9e` your requests are now working. 

```r
a <- marinetrophicindex("eez", 76)
b <- marinetrophicindex("eez", 76, type = "rmti")
d <- marinetrophicindex("eez", 76, type = "fib_index")
Map(function(x) head(x, 3), list(a,b,d))

[[1]]
  level year
1  3.43 1950
2  3.44 1951
3  3.46 1952

[[2]]
  level_1950 level_1962 level_1968 year
1      3.430         NA         NA 1950
2      3.435         NA         NA 1951
3      3.443         NA         NA 1952

[[3]]
  level year
1  0.00 1950
2  0.01 1951
3  0.16 1952
```
To install the dev version run
```r
install.packages("devtools")
devtools::install_github("ropensci/rseaaroundus")
```

**Comment by Xeonilian** [comment]
Thanks a lot, it worked.

BTW, When I installed the new viersion. the dependent package rgdal could not be installed automatically.
So I installed it myself, and then rseaaroundus.

Perhaps the error message is usefull, I attach it here.

> Downloading GitHub repo ropensci/rseaaroundus@master
> from URL https://api.github.com/repos/ropensci/rseaaroundus/zipball/master
> Installing seaaroundus
> Installing 1 package: rgdal
> trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/bin/windows/contrib/3.3/rgdal_1.2-6.zip'
> Content type 'application/zip' length 15942579 bytes (15.2 MB)
> downloaded 15.2 MB
> 
> package ‘rgdal’ successfully unpacked and MD5 sums checked
> Warning: cannot remove prior installation of package ‘rgdal’
> 
> The downloaded binary packages are in
> 	C:\Users\AppData\Local\Temp\RtmpKIJ7zt\downloaded_packages
> "G:/R-3.3.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>   "C:/Users/garde/AppData/Local/Temp/RtmpKIJ7zt/devtools3384736f6358/ropensci-rseaaroundus-d405c9e"  \
>   --library="G:/R-3.3.2/library" --install-tests 
> 
> ERROR: dependency 'rgdal' is not available for package 'seaaroundus'
> * removing 'G:/R-3.3.2/library/seaaroundus'
> Error: Command failed (1)

**Comment by patperu** [comment]
Thank you for reporting the error. Unfortunately I can't help you with this issue. But I'm sure Scott has an explanation.

**Comment by Xeonilian** [comment]
@patperu 
I just tried the solution without noticing who suggested. I thought you were Scott, so reported the error to you. Thanks again.

**Comment by sckott** [comment]
@Xeonilian getting to this soon

**Comment by sckott** [comment]
looks like we're all good here - @Xeonilian that warning for rgdal is i think because you had rgdal loaded when you were installing it, so not a big deal i think
