### ISSUE TITLE
getcelldata() function does not return data from multiple cells

### ISSUE THREAD

**Issue by dtickler** [ropensci/seaaroundus#16]
Hi there,

I am trying to use the getcelldata() function to extract large blocks of cells, but the data returned is only for the first cell in the list (i.e. getcelldata(2005, c(89568,90288,89569)) only returns data for cell 89568)

Is this a case of operator error, or a bug in the code?

Am running R version 3.3.1 with R Studio Version 1.0.143 on Mac OSX 10.11.6

Ideally, I would like to be able to extract data for a range of years and cells using a single call to getcelldata() rather than using a loop to call each year/cell combination individually! Does the API allow this?

Thanks,

Dave

**Comment by ableitner** [comment]
Running R version 3.2.2 on Mac OSX 10.12 I get 
> dim(getcelldata(2005, c(89568,90288,89569)))
[1] 132  18

Maybe just upgrading your R version would help?

**Comment by dtickler** [comment]
Yep. Good suggestion!

**Comment by sckott** [comment]
thanks @ableitner
