### ISSUE TITLE
regionmap fucntion returning an error

### ISSUE THREAD

**Issue by LaureVelez** [ropensci/seaaroundus#18]
Hi there,

I tried to run the regionmap function and I got an error
This is the command line in the help document
 > regionmap("eez", 76)
Error in ogrListLayers(url) : Cannot open data source

Thanks,

Laure

**Comment by sckott** [comment]
thanks, can you share you session info please

**Comment by LaureVelez** [comment]
Yes, sure,
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

Thanks

**Comment by sckott** [comment]
the session info would be everything printed out when you run `sessionInfo` or `devtools::session_info()` when `seaaroundus` is loaded e.g., mine is 

```r
R version 3.4.0 Patched (2017-06-05 r72770)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] seaaroundus_1.0.1.9146 devtools_1.13.2       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11       lattice_0.20-35    digest_0.6.12      withr_1.0.2        R6_2.2.2           grid_3.4.0        
 [7] plyr_1.8.4         jsonlite_1.5       gtable_0.2.0       scales_0.4.1       httr_1.2.1         ggplot2_2.2.1.9000
[13] rlang_0.1.1        lazyeval_0.2.0     sp_1.2-4           rgdal_1.2-7        tools_3.4.0        munsell_0.4.3     
[19] maps_3.2.0         compiler_3.4.0     colorspace_1.3-2   memoise_1.1.0      tibble_1.3.3 
```

**Comment by sckott** [comment]
Try loading the pkg first, then running that example code, and what happens?

**Comment by sckott** [comment]
weird errors think ive seen before from `rgdal`, looking into switching to using `sf` package

**Comment by sckott** [comment]
@LaureVelez  just made a change, reinstall `devtools::install_github("ropensci/seaaroundus")`, restart session, then try again

using `sf` pkg now, so depending on your OS, you may need a special step to install it, but it may go fine

**Comment by LaureVelez** [comment]
thanks, I am also using sf package for other stuff
We progress, now I obtain this error
>regionmap("eez",76)
Regions defined for each Polygons
Regions defined for each Polygons
Warning: Ignoring unknown aesthetics: x, y
Warning: Ignoring unknown aesthetics: x, y
Regions defined for each Polygons
Warning: Ignoring unknown aesthetics: x, y
Error in maptype(database) : objet 'C_map_type' introuvable

Thanks,

**Comment by sckott** [comment]
Still didn't get your complete session info, please share that

**Comment by LaureVelez** [comment]
sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] seaaroundus_1.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11     lattice_0.20-33  digest_0.6.12    withr_1.0.2      grid_3.3.1       R6_2.1.3         plyr_1.8.4      
 [8] jsonlite_1.5     gtable_0.2.0     git2r_0.15.0     scales_0.4.1     ggplot2_2.2.1    httr_1.2.1       rlang_0.1.1     
[15] lazyeval_0.2.0   curl_2.0         rstudioapi_0.6   sp_1.2-4         devtools_1.12.0  rgdal_1.2-7      tools_3.3.1     
[22] munsell_0.4.3    maps_3.2.0       colorspace_1.2-6 memoise_1.0.0    tibble_1.3.3

**Comment by sckott** [comment]
This is the current version https://github.com/ropensci/seaaroundus/blob/master/DESCRIPTION#L5 

You didn't actually do the update or you didn't restart your R session after updating

**Comment by LaureVelez** [comment]
I did the update and restart my session, but installing it I obtained an error
devtools::install_github("ropensci/seaaroundus")
Downloading GitHub repo ropensci/seaaroundus@master
from URL https://api.github.com/repos/ropensci/seaaroundus/zipball/master
Installing seaaroundus
Downloading GitHub repo ropensci/wicket@master
from URL https://api.github.com/repos/ropensci/wicket/zipball/master
Erreur : Could not find build tools necessary to build wicket

**Comment by sckott** [comment]
does this work for you: `install.packages("wicket")`

**Comment by LaureVelez** [comment]
Yes, the installation of the wicket package is working but i stil obtain the same error

> devtools::install_github("ropensci/seaaroundus")
Downloading GitHub repo ropensci/seaaroundus@master
from URL https://api.github.com/repos/ropensci/seaaroundus/zipball/master
Installing seaaroundus
Downloading GitHub repo ropensci/wicket@master
from URL https://api.github.com/repos/ropensci/wicket/zipball/master
Erreur : Could not find build tools necessary to build wicket

**Comment by sckott** [comment]
does `devtools::has_devel()` return `TRUE` ? if `FALSE`, then run `devtools::find_rtools()`, then run `devtools::has_devel()` again and it should then return `TRUE`

**Comment by sckott** [comment]
closing due to inactvity - 

though opening a new issue b/c this functioning is now causing R to crash due to a geos error
