### ISSUE TITLE
Is it possible to include the scientific name of the fished species and their trophic level?

### ISSUE THREAD

**Issue by marco198** [ropensci/seaaroundus#2]
Hello everybody,
I think that It would be great to include the scientific name and trophic levels of the caught species in addition to the 'taxon' level of aggregation, for example, in the form catchdata('lme', 10, dimension='scientificname', tl=T)
thank you

**Comment by jafflerbach** [comment]
This would also be immensely helpful for us at the Ocean Health Index. We need to match scientific names with information from FishBase. It seems that currently the only way to get scientific names is to query the data by cell.

**Comment by EvilScott** [comment]
Scientific name is possible since the scientific name comes with the API response for taxon, we just need to add some code to handle this special case. Code would go [here](https://github.com/SeaAroundUs/rseaaroundus/blob/master/R/catchdata.R#L38)

TL not so much since its a separate endpoint.

**Comment by sckott** [comment]
any thoughts on this @EvilScott ?  is it not likely to happen (in which case close issue), or still possible (in which case, keep open)

**Comment by EvilScott** [comment]
not likely to happen, sorry. i am no longer at vulcan so i dont work with this data anymore.

**Comment by sckott** [comment]
got it, thx

**Comment by sckott** [comment]
@Gtsui091 I think you still work with SAU?  Is this feature request something likely to happen?

**Comment by Gtsui091** [comment]
Hi @sckott, yup I still work at SAU. I will try to make this happen but I won't have time to do it until december cause working on getting the latest version of our data on the web

**Comment by sckott** [comment]
@Gtsui091 thanks much

**Comment by jcvdav** [comment]
Is there an update on this? It would be great to have the scientific names, at least as a dictionary to manually `left_join` them to data downloaded via `catchdata()`. This would allow matching SAU data to other information (*e.g.* RAM or FAO).

I'm thinking a workflow like this could work with the dictionary:

```
#Get a dictionary with columns for common and scientific name
dictionary <- seaaroundus::dictionary()

# Get some catch data
sau_catches <- seaaroundus::catchdata(region = "global",
                                       measure = "tonnage",
                                       dimension = "taxon",
                                       id = "global",
                                       limit = 10)
# Tidy data and add scientific name
my_catches <- sau_catches %>%
    gather(common, catches, -year) %>%
    left_join(dictionary, by = "common")

# my_catches now has scientific names, and can be matched to other data
```

I tried creating a dictionary using `rfishbase::common_to_sci(x = "Atlantic bluefin tuna")` for example, but that returns `[1] "Thunnus thynnus"    "Thunnus orientalis"`, which are the Pacific and Atlantic bluefin tuna. However, if pointed in the right direction wiithin the SAU data, I am happy to create the dictionary and add a function to load it (similar to how `rfishbase::species()` works) and submit a PR.

**Comment by jcvdav** [comment]
That's it @sckott!

Perhaps `catchdata` can take another argument (*i.e.* `sci_name = F`), and then [line 45 in `catchdata`](https://github.com/ropensci/seaaroundus/blob/master/R/catchdata.R#L45) can be 

```
  # Add scientific names if required
  if(sci_name){
    colnames(df) <- c("years", data$scientific_name)
  } else {
    colnames(df) <- tolower(c("years", data$key))
  }
```

This way, a call to `catchdata` with `sci_name = F` (or not specified):

```
catchdata(region = "global",
          measure = "tonnage",
          dimension = "taxon",
          id = "global",
          limit = 1,
          sci_name = F) %>%
  head()
```
Gives
```
  years anchoveta   others
1  1950  13071.28 28453291
2  1951  28229.38 30575118
3  1952  34216.01 32395393
4  1953  56514.98 33331451
5  1954  63340.52 36286943
6  1955  79173.43 38542950
```
And setting `sci_name = T`:
```
catchdata(region = "global",
          measure = "tonnage",
          dimension = "taxon",
          id = "global",
          limit = 1,
          sci_name = T) %>%
  head()
```
Gives:
```
  years engraulis ringens       NA
1  1950          13071.28 28453291
2  1951          28229.38 30575118
3  1952          34216.01 32395393
4  1953          56514.98 33331451
5  1954          63340.52 36286943
6  1955          79173.43 38542950
```

I'm happy to make the changes to `catchdata`, managing for NA's (for example, when `key` is `"others"`, `scientific_name` is `NA`) and submit a PR. I've already got the changes in a local function.

**Comment by sckott** [comment]
would it be more or less useful to have the data in a long format, like so, adding scientific name and entity_id

```r
   years      name        tons           sciname entity_id
1   1950 anchoveta    13071.28 Engraulis ringens    600004
2   1951 anchoveta    28229.38 Engraulis ringens    600004
3   1952 anchoveta    34216.01 Engraulis ringens    600004
4   1953 anchoveta    56514.98 Engraulis ringens    600004
5   1954 anchoveta    63340.52 Engraulis ringens    600004
6   1955 anchoveta    79173.43 Engraulis ringens    600004
7   1950    others 28453291.17              <NA>        NA
8   1951    others 30575117.81              <NA>        NA
9   1952    others 32395393.34              <NA>        NA
10  1953    others 33331451.09              <NA>        NA
11  1954    others 36286942.71              <NA>        NA
12  1955    others 38542950.46              <NA>        NA
```

**Comment by sckott** [comment]
that way we can have both common and sci. names and any other data as additional columns

**Comment by jcvdav** [comment]
Yes!

I didn't suggest that because people might be used to `catchdata` returning a wide format, and perhaps changing it would cause compatibility issues.

That said, the first thing I always do is to convert to long format, so that output would be perfect.

**Comment by sckott** [comment]
Cool. Can you send a PR then with the changes?

**Comment by sckott** [comment]
package is being archived
