### ISSUE TITLE
getcelldata

### ISSUE THREAD

**Issue by stefankfu** [ropensci/seaaroundus#20]
Hi there,

when I am retrieving data using getcelldata there is one variabel which states the catch in a cell "catchsum". Do you know how this is measured? Is it tonnage or catch value? And in which unit is it measured? 

I have digged through the seaaroundus documentation but was not able to find some defintion of the variables from getcelldata.

Thanks a lot!
Stefan

**Comment by Gtsui091** [comment]
Hi Stefan,

"catchsum" is measured in metric tonnes. 

Are there other parameters you are unsure about?

Thanks,
Gordon

**Comment by stefankfu** [comment]
Thanky you so much for the quick answer! I think the other parameters are pretty clear. Maybe one last question - is it safe to say that total catch in a cell and year and taxonomy = SUM^(over all fishing entities) (discards+landings)?

**Comment by Gtsui091** [comment]
Hi Stefan,

I'm not really understanding what your equation is. This is a link to our methods which explains how we allocate our catch data to 1/2 degree x 1/2 degree cells. 
http://www.seaaroundus.org/catch-reconstruction-and-allocation-methods/#_Toc421534366
I think your answer will be in there. If it doesn't, feel free to ask me.

**Comment by jafflerbach** [comment]
@stefankfu - I have been calculating total catch per cell/taxon/year as:

```catch = sum(LSF_CR,SSF_CR,IUU_CR,Discards_CR,na.rm=T)```

which is the total amount of catch caught by large scale fishing (LSF), small scale fishing (SSF), illegal and unreported (IUU) and discards. I would assume this is accurate but if this interpretation is wrong, @Gtsui091, please let us know

**Comment by Gtsui091** [comment]
@jafflerbach by LSF and SSF you mean Landings right? If so, then yes that is correct.

@stefankfu I think I understand now. Yes if you sum up up the Landings and Discards from the catch_status_name column for all fishing entities in that cell for that year, that will be the total catch.

**Comment by sckott** [comment]
i think we're all sorted here, closing. reopen if i guessed wrong
