### ISSUE TITLE
Fatal Error installing github("ropensci/seaaroundus")

### ISSUE THREAD

**Issue by theAbby** [ropensci/seaaroundus#22]
Hi 

Have had this happen on 2 different computers now. Both windows, one Windows 7, one Windows 10. Chrome default browser. Running R through R studio.

2 fatal errors occurring when trying to install the github. Previously (resolved-I think) fatal error as wicket is needed, so downloaded this package and tried again. Fatal error states, both for i386 & x64 that there is no file, when referring to location it automatically stashed the libraries earlier. Has been referencing this folder though out, so odd

"
  *** arch - i386
**Fatal error: cannot open file 'D:\Documents': No such file or directory**
*** arch - x64
Fatal error: cannot open file 'D:\Documents': No such file or directory
"

Thought perhaps it was due to there being a space in parent folder 'Documents and Settings' (which is a folder I can not adjust=work computer) and was assured by IT that people use R with this standard folder all the time.

Thoughts? Feelings? 
Help most appreciated.

<installing to D:/Documents and Settings/acramer/Documents/R/win-library/3.4/wicket/libs/x64
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
**Fatal error: cannot open file 'D:\Documents': No such file or directory**

*** arch - x64
Fatal error: cannot open file 'D:\Documents': No such file or directory

ERROR: loading failed for 'i386', 'x64'
* removing 'D:/Documents and Settings/acramer/Documents/R/win-library/3.4/wicket'
* restoring previous 'D:/Documents and Settings/acramer/Documents/R/win-library/3.4/wicket'
Installation failed: Command failed (1)
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL "D:/Documents and  \
  Settings/acramer/AppData/Local/Temp/RtmpS6vb3p/devtools33d41c8a6dbd/ropensci-seaaroundus-e139b30"  \
  --library="D:/Documents and  \
  Settings/acramer/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'seaaroundus' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Fatal error: cannot open file 'D:\Documents': No such file or directory

*** arch - x64
Fatal error: cannot open file 'D:\Documents': No such file or directory

ERROR: loading failed for 'i386', 'x64'
* removing 'D:/Documents and Settings/acramer/Documents/R/win-library/3.4/seaaroundus'
Installation failed: Command failed (1)>

```r

```
</details>

**Comment by sckott** [comment]
where is your session info?

**Comment by sckott** [comment]
can you install any other pkgs with `install_github` ?

**Comment by theAbby** [comment]
Oop! Sorry there. 

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

Hm. I can not. Same error- going to the boards-thanks for a lead! Will report back if I fix.

**Comment by theAbby** [comment]
Solution found- Space meant that it was looking for a file not in existance (ie D'Documents' vs 'Documents and Settings') Since I could not change folder name, nor path name, made a new folder called 'Documents'

RTools was acting up and not playing well with github. Needed rerouting as well.
