### ISSUE TITLE
getcalldata() no rows, no collumns- Issue 6 reoccurring (please see notes there)

### ISSUE THREAD

**Issue by theAbby** [ropensci/seaaroundus#23]
Hi.
I'm having this thread issue now: using R (3.4)- latest version

-able to getcells() no problem, lots of ways
-getcelldata() returning data frame with 0 columns and 0 rows, in many instances
-no warning nor error thrown.

**Comment by sckott** [comment]
thanks @theAbby will have a look

**Comment by sckott** [comment]
@theAbby  can you  gives some examples

**Comment by sckott** [comment]
closing no response
