### ISSUE TITLE
get cell coordinates

### ISSUE THREAD

**Issue by robertspm** [ropensci/seaaroundus#27]
Is there a way to get the latitude/longitude coordinates of each one in a set of cells? I have the numbers of the cells I need and the data in them, but no way to know which cell is which. I have read the methods, so I understand that the top left bounding box corner coordinate is at 90°N and 180°W, but is there an easy way to find out at least one corner or the center point for a subset of cells?

**Comment by robertspm** [comment]
Thanks for the quick reply! Yes, I am sharing below. It's pretty simple really, but I want to be able to map the results in GIS, so I need to know where each cell is. I could even use a simple reference table outside of R, but I can't find the cell coordinates anywhere online. 

I ran the below, then pulled all the data for 2010-2014 for each cell.

small_cells <- getcells("POLYGON((40.80421	-2.48108,
42.5893	12.36285,
55.31404	15.10565,
55.57297	8.05186,
51.17598	1.05347,
43.99827	-5.48387,
40.80421	-2.48108
))")

catch2010_100 <- getcelldata(2010, cells = small_cells[1:100]) 
etc.

I couldn't pull all the data at once, so I ran it in batches like the example above, then combined the datasets. If you need something else, let me know. I'm relatively new to R, so hopefully this is what you asked for. 

Session info
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] seaaroundus_1.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15     lattice_0.20-35  R6_2.2.2         crul_0.5.0       grid_3.4.3       plyr_1.8.4      
 [7] jsonlite_1.5     gtable_0.2.0     scales_0.5.0     ggplot2_2.2.1    pillar_1.1.0     rlang_0.1.6     
[13] curl_3.1         lazyeval_0.2.1   sp_1.2-7         tools_3.4.3      munsell_0.4.3    maps_3.2.0      
[19] compiler_3.4.3   colorspace_1.3-2 tibble_1.4.2

**Comment by sckott** [comment]
thanks @robertspm 

@Gtsui091 Is there anyway to get coordinates for the Seaaroundus cells?  Either their centroids, or their East/west/south/north points, or something?

**Comment by sckott** [comment]
@robertspm i know of no way to get the coordinates for the cells, ^^ asked above

**Comment by Gtsui091** [comment]
Hi sorry for the delayed response. I do have a cell table with the cell ids that correspond to the long/lat of the centroid of the cell. I'm not sure how to integrate it with the R package though since its not one of the tables currently used by the website so its not in the API. I think I would have to modify our API first to include the table before it can called by the R package

**Comment by robertspm** [comment]
Hi, that's great news! Rather than going through all of that, could you send me the standalone table as a csv?

**Comment by sckott** [comment]
thanks @Gtsui091 - that'd be great if you could integrate into the API. 

@robertspm maybe they will send it to you, but it would be best in the long run if it's in the API for others to use as well

**Comment by Gtsui091** [comment]
@robertspm I can do that. Shoot me an email and I can send it over to you. g.tsui@oceans.ubc.ca

@sckott I'll definitely try to make more time now. Just been completely swamped the past few months

**Comment by robertspm** [comment]
@sckott Absolutely, but in the meantime, thank you @Gtsui091! I just sent you an email.

**Comment by sckott** [comment]
Any updates on this @Gtsui091 ?

**Comment by sckott** [comment]
Any updates on this @Gtsui091  ?

**Comment by sckott** [comment]
@Gtsui091 @LinhTran any thoughts?
