### ISSUE TITLE
Mariculture data download by species

### ISSUE THREAD

**Issue by jatalah** [ropensci/seaaroundus#30]
Hi,

Is it possible to add a function to download the mariculture data by species and country, including the coordinates of State/Provinces shown in the website maps?

Thanks

**Comment by sckott** [comment]
@Gtsui091 @LinhTran  any ideas about this?

**Comment by sckott** [comment]
@Gtsui091 @LinhTran any thoughts?

**Comment by sckott** [comment]
@Gtsui091 @LinhTran any ideas about this?

**Comment by Gtsui091** [comment]
Hey Scott, I spoke with Deng and the Mariculture data is being updated by an external collaborator. The structure of the data is slightly different from our current one so they still need to discuss how to incorporate it. I, unfortunately, I don't have a timeline for this so I think this ticket can be closed for now. Requests for mariculture data can contact Sea Around Us to reach the collaborator.

**Comment by sckott** [comment]
okay, thanks @Gtsui091 

@jatalah see above, "Requests for mariculture data can contact Sea Around Us to reach the collaborator."
