### ISSUE TITLE
getcelldata returning only one value 

### ISSUE THREAD

**Issue by LaureVelez** [ropensci/seaaroundus#7]
Hi there,

First, thanks to have fixed the problem with the api but ...
I'm trying the 'getcelldata' and, running the example, I can only get the result for one cell (the first one). 

cells <- getcells("POLYGON ((-48.177685950413291 15.842380165289299,-48.177685950413291 15.842380165289299,
-54.964876033057919 28.964280991735578,-35.960743801652967 27.606842975206646,-48.177685950413291
15.842380165289299))")

Following the example, the polygon intersects with 547 cells of the grid but doing this command : 
# get datagrid of cell data for a given year and list of cells

d <- getcelldata(2005, cells)

I only obtain the result for the first cell even if I give a vector of cells as argument.

I guess that it should be a list or an array?

After that, I would like to know the proportion of my polygon which is intersecting with the grid. How can I obtain the grid as a gis format?

Thanks a lot,

Laure

**Comment by EvilScott** [comment]
@LinhTran can you check the query used by `sunfish.spatial.CellCatch.get` method on the SAU API for this issue?

**Comment by EvilScott** [comment]
@LinhTran can you also assist in providing the grid as GIS format per @LaureVelez request?

**Comment by LinhTran** [comment]
I can look into the query used by sunfish.spatial.CellCatch.get, np.

But for the second request, do we already have an API to return GIS format? An existing output format parameter, maybe. If not, then we would need to expand the existing API to accept an output format param or provide a new API altogether. As for the actual format, having a list of cell IDS on hand, would only a matter of converting them in to a geojson structure and return to the user. Unless GIS format here really means the binary shape file format?

**Comment by EvilScott** [comment]
@LinhTran I don't think we currently have an API endpoint to support returning the entire grid, so I think this can be delivered via API. Perhaps it is appropriate to allow downloading of shape files or another format somewhere else?

**Comment by EvilScott** [comment]
@LaureVelez it looks like there is an issue with the list comprehension reading the API response. Probably need to adjust this line here: https://github.com/SeaAroundUs/rseaaroundus/blob/master/R/spatial.R#L24

I'll see if I can find time to get to this soon

**Comment by LaureVelez** [comment]
Thank you for your reactive response. I can manage by using the getcelldata function cells by cells. Actually, i just need the proportion of the cell intersecting with my polygons. Thanks

**Comment by LaureVelez** [comment]
Is that possible to know if you found time to work on that bug? Or there is an other way to get the grid as gis format? Thanks a lot

**Comment by EvilScott** [comment]
@LinhTran  can i assign this to you?

**Comment by James-Thorson** [comment]
First off, this looks like a very useful project -- thanks for the effort!

I'm exploring the examples and when I try...

```R
library(seaaroundus)
getcelldata( year=2005, cells=c(89568,90288,89569))
```

... from the GitHub main page, I get as output `data frame with 0 columns and 0 rows`.  I'm using R version 3.2.2 on a windows machine.  I imagine this is not the intended output, no?

**Comment by sckott** [comment]
👋  @LaureVelez  @James-Thorson  

this should be fixed now, try again after reinstall from github like `devtools::install_github("ropensci/seaaroundus")`
